# Generated by Django 2.1 on 2018-08-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actcode', '0002_auto_20180820_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reference',
            field=models.TextField(null=True),
        ),
    ]
