# Generated by Django 2.1 on 2018-08-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actcode', '0003_document_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tokens',
            field=models.BinaryField(null=True),
        ),
    ]
