# Generated by Django 2.1 on 2018-09-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actcode', '0004_document_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tokens',
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
