# Generated by Django 2.1 on 2018-09-10 15:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


def create_sessions(apps, schema_editor):
    Annotation = apps.get_model('actcode', 'Annotation')
    Session = apps.get_model('actcode', 'Session')
    projects = list(Annotation.objects.order_by("document__project", "document__gold").values_list("document__project", "document__gold").distinct())
    for project, gold in projects:
        s = Session.objects.create(train=(not gold), description="Migrated annotations", project_id=project)
        Annotation.objects.filter(document__project_id=project, document__gold=gold).update(session=s)

class Migration(migrations.Migration):

    dependencies = [
        ('actcode', '0008_auto_20180910_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train', models.BooleanField()),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actcode.Project')),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actcode.Session'),
        ),
        migrations.RunPython(create_sessions),
        migrations.AlterField(
            model_name='annotation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actcode.Session'),
        ),
    ]
