# Generated by Django 2.1 on 2018-09-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actcode', '0009_auto_20180910_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='label',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='actcode.Label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='query',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='state',
            field=models.TextField(null=True),
        ),
    ]
