# Generated by Django 2.1 on 2018-09-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actcode', '0010_auto_20180913_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='model_location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='model_timestamp',
        ),
    ]
