# Generated by Django 2.1 on 2018-09-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actcode', '0011_auto_20180913_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='populate_task_id',
            field=models.TextField(null=True),
        ),
    ]
