# Generated by Django 2.1 on 2018-09-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actcode', '0012_session_populate_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
    ]
